name: libwasmer-build-shim-mac-arm64

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build shim library for MacOS ARM64
    runs-on: macos-13-xlarge
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.7
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Build library
        run: |
          cd ./capi_shim
          go build -buildmode=c-shared -ldflags="-w" -o $GITHUB_WORKSPACE/libwasmer_darwin_arm64_shim.dylib .
          install_name_tool -id @rpath/libwasmer_darwin_arm64_shim.dylib $GITHUB_WORKSPACE/libwasmer_darwin_arm64_shim.dylib

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            libwasmer_darwin_arm64_shim.dylib
          if-no-files-found: error
